# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane


ENV["FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD"] = "okpm-sfyt-fjpu-unck"
default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    build_app(export_xcargs: "-allowProvisioningUpdates")
    #build_app(scheme: "Insane Circuit")
    upload_to_testflight(username: "anderson.sjav@gmail.com")
  end
end
